/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransaksiRouteImport } from './routes/transaksi'
import { Route as SiswaRouteImport } from './routes/siswa'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'

const TransaksiRoute = TransaksiRouteImport.update({
  id: '/transaksi',
  path: '/transaksi',
  getParentRoute: () => rootRouteImport,
} as any)
const SiswaRoute = SiswaRouteImport.update({
  id: '/siswa',
  path: '/siswa',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/scan': typeof ScanRoute
  '/siswa': typeof SiswaRoute
  '/transaksi': typeof TransaksiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/scan': typeof ScanRoute
  '/siswa': typeof SiswaRoute
  '/transaksi': typeof TransaksiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/scan': typeof ScanRoute
  '/siswa': typeof SiswaRoute
  '/transaksi': typeof TransaksiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/scan' | '/siswa' | '/transaksi'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/scan' | '/siswa' | '/transaksi'
  id: '__root__' | '/' | '/login' | '/scan' | '/siswa' | '/transaksi'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ScanRoute: typeof ScanRoute
  SiswaRoute: typeof SiswaRoute
  TransaksiRoute: typeof TransaksiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transaksi': {
      id: '/transaksi'
      path: '/transaksi'
      fullPath: '/transaksi'
      preLoaderRoute: typeof TransaksiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/siswa': {
      id: '/siswa'
      path: '/siswa'
      fullPath: '/siswa'
      preLoaderRoute: typeof SiswaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ScanRoute: ScanRoute,
  SiswaRoute: SiswaRoute,
  TransaksiRoute: TransaksiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
